fix installer

diff --git a/pear/airootfs/usr/share/pearOS-installer/system_install/setup b/pear/airootfs/usr/share/pearOS-installer/system_install/setup
--- a/pear/airootfs/usr/share/pearOS-installer/system_install/setup
+++ b/pear/airootfs/usr/share/pearOS-installer/system_install/setup
@@ -4,16 +4,15 @@
   error_exit() {
     local error_message="$1"
     echo "INSTALLATION FAILED: $error_message" | tr -d '\n' > /tmp/progress
-    echo "ERROR: $error_message" >> /tmp/install.log
+    echo "ERROR: $error_message" >> /home/liveuser/Desktop/install.log
     exit 1
   }
 
-  # Trap pentru erori neașteptate
   trap 'error_exit "Unexpected error at line $LINENO"' ERR
 
   # Setting usefull variables
   DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-  BASE_PACKAGES=( 'linux617' 'archlinux-keyring' 'alsa-utils' 'amd-ucode' 'arch-install-scripts' 'b43-fwcutter' 'base' 'bind-tools' 'broadcom-wl' 'btrfs-progs' 'clonezilla' 'cloud-init' 'crda' 'cryptsetup' 'darkhttpd' 'ddrescue' 'dhclient' 'dhcpcd' 'diffutils' 'dmraid' 'dnsmasq' 'dosfstools' 'e2fsprogs' 'edk2-shell' 'efibootmgr' 'espeakup' 'ethtool' 'exfatprogs' 'f2fs-tools' 'fatresize' 'fsarchiver' 'gnu-netcat' 'gpart' 'gpm' 'gptfdisk' 'grml-zsh-config' 'hdparm' 'intel-ucode' 'irssi' 'iwd' 'jfsutils' 'linux' 'linux-atm' 'linux-firmware' 'livecd-sounds' 'lsscsi' 'lvm2' 'man-db' 'man-pages' 'mc' 'mdadm' 'memtest86+' 'mkinitcpio' 'mkinitcpio-archiso' 'mkinitcpio-nfs-utils' 'modemmanager' 'mtools' 'nano' 'nbd' 'ndisc6' 'nfs-utils' 'nilfs-utils' 'ntfs-3g' 'nvme-cli' 'openssh' 'parted' 'partimage' 'ppp' 'pptpclient' 'reflector' 'reiserfsprogs' 'rp-pppoe' 'rsync' 'sdparm' 'sg3_utils' 'smartmontools' 'sof-firmware' 'squashfs-tools' 'sudo' 'syslinux' 'systemd-resolvconf' 'tcpdump' 'testdisk' 'udftools' 'usb_modeswitch' 'usbmuxd' 'usbutils' 'vpnc' 'wireless-regdb' 'wireless_tools' 'wpa_supplicant' 'wvdial' 'xfsprogs' 'xl2tpd' 'zsh' 'xorg' 'sddm' 'bash-completion' 'networkmanager' 'linux-headers' 'base-devel' 'git' 'xf86-input-libinput' 'pacman-contrib' 'plasma' 'konsole' 'kate' 'nautilus' 'xdg-user-dirs' 'ark' 'gnome-software' 'gnome-software-packagekit-plugin' 'appmenu-gtk-module' 'touchegg' 'rhythmbox' 'latte-dock' 'kvantum' 'gambas3-runtime' 'pearos-grub-theme' 'theme-switcher-bin' 'system-overview' 'system-update' 'pearos-settings' 'kwin-effects-yet-another-magic-lamp' 'gambas3-gb-image' 'gambas3-gb-form' 'gambas3-gb-qt5' 'gambas3-gb-gtk3' 'system-update' 'python-pip' 'neofetch' 'grub' 'os-prober' 'firefox' 'ttf-roboto' 'gvfs' 'pavucontrol' 'pulseaudio' 'pulseaudio-alsa' 'ttf-dejavu' 'xorg-apps' 'xorg-server' 'npm' 'electron')
+  BASE_PACKAGES=('archlinux-keyring' 'alsa-utils' 'amd-ucode' 'arch-install-scripts' 'b43-fwcutter' 'base' 'bind-tools' 'broadcom-wl' 'btrfs-progs' 'cloud-init' 'crda' 'cryptsetup' 'darkhttpd' 'dhclient' 'dhcpcd' 'diffutils' 'dnsmasq' 'e2fsprogs' 'edk2-shell' 'efibootmgr' 'espeakup' 'ethtool' 'exfatprogs' 'f2fs-tools' 'fatresize' 'fsarchiver' 'openbsd-netcat' 'gpart' 'gpm' 'gptfdisk' 'grml-zsh-config' 'hdparm' 'intel-ucode' 'iwd' 'jfsutils' 'linux617' 'linux-firmware' 'livecd-sounds' 'lsscsi' 'lvm2' 'man-db' 'man-pages' 'mc' 'mdadm' 'memtest86+' 'mkinitcpio' 'mkinitcpio-archiso' 'mkinitcpio-nfs-utils' 'modemmanager' 'mtools' 'nano' 'nbd' 'ndisc6' 'nfs-utils' 'nilfs-utils' 'ntfs-3g' 'nvme-cli' 'parted' 'partimage' 'rp-pppoe' 'rsync' 'sdparm' 'sg3_utils' 'smartmontools' 'sof-firmware' 'sudo' 'syslinux' 'systemd-resolvconf' 'tcpdump' 'testdisk' 'udftools' 'usb_modeswitch' 'usbmuxd' 'usbutils' 'vpnc' 'wireless-regdb' 'wireless_tools' 'wpa_supplicant' 'xfsprogs' 'xl2tpd' 'zsh' 'xorg' 'sddm' 'bash-completion' 'networkmanager' 'linux-headers' 'base-devel' 'git' 'xf86-input-libinput' 'pacman-contrib' 'plasma' 'konsole' 'kate' 'nautilus' 'xdg-user-dirs' 'ark' 'gnome-software' 'appmenu-gtk-module' 'touchegg' 'rhythmbox' 'kvantum' 'pearos-grub-theme' 'pearos-settings' 'python-pip' 'neofetch' 'grub' 'os-prober' 'firefox' 'ttf-roboto' 'gvfs' 'pavucontrol' 'pulseaudio' 'pulseaudio-alsa' 'ttf-dejavu' 'xorg-apps' 'xorg-server' 'kcalc' 'gwenview' 'elisa' 'npm' 'electron')
   UEFI=false
   bluetooth=false
   installed=false
@@ -43,10 +42,16 @@
   DESKTOP_PACKAGES+=("${DESKTOP_DEFAULTS[@]}")
   DESKTOP_PACKAGES+=('plasma-nm')
 
+  # Helper function to update progress (0-100)
+  update_progress() {
+    local progress="$1"
+    echo "$progress" | tr -d '\n' > /tmp/progress
+  }
+
   # Set/load the US keymap
   localectl set-keymap "$KEYMAP"
   loadkeys "$KEYMAP"
-  echo "2" | tr -d '\n' > /tmp/progress
+  update_progress "3"
 
   # Check if the system is UEFI or legacy
   if [ -d /sys/firmware/efi ]; then
@@ -54,7 +59,7 @@
   fi
 
   # Check if the system has bluetooth or not
-  if dmesg | grep -iq "blue"; then
+  if lsusb | grep -i bluetooth || lspci | grep -i bluetooth; then
     bluetooth=true
   fi
 
@@ -69,7 +74,7 @@
   else
     parted -s "$DISK" mklabel msdos &> /dev/null
   fi
-  echo "4" | tr -d '\n' > /tmp/progress
+  update_progress "5"
 
   # Partition creating, for UEFI systems, with swap memory check.
   if $UEFI; then
@@ -98,20 +103,20 @@
       echo -e "n\np\n1\n\n\nw" | fdisk "$DISK" &> /dev/null
     fi
   fi
-  echo "8" | tr -d '\n' > /tmp/progress
+  update_progress "8"
 
   # Make the ext4 filesystem
   if ! mkfs."$FILE_SYSTEM" "$ROOT_PART" &> /dev/null; then
     error_exit "Failed to create filesystem on $ROOT_PART"
   fi
-  echo "10" | tr -d '\n' > /tmp/progress
+  update_progress "10"
 
   # Mount the disk to /mnt and commit that into the variable
   if ! mount "$ROOT_PART" /mnt; then
     error_exit "Failed to mount $ROOT_PART to /mnt"
   fi
   mounted=true
-  echo "12" | tr -d '\n' > /tmp/progress
+  update_progress "12"
 
   # If the system is UEFI enabled, the boot partition gets mounted
   if $UEFI; then
@@ -173,41 +178,68 @@
         *) DESKTOP_PACKAGES+=('xf86-video-fbdev') ;;
       esac
     fi
-   echo "15" | tr -d '\n' > /tmp/progress
+  update_progress "15"
 
   # adding pacman config directly
   mkdir -p /mnt/etc/
   cp /etc/pacman.conf /mnt/etc/pacman.conf
-  echo "17" | tr -d '\n' > /tmp/progress
+  update_progress "17"
 
-  # installing packages using pacstrap from the BASE_PACKAGES array variable
-  # Flag --needed evită reinstalarea pachetelor deja instalate
-  # Iterăm prin pachete pentru a continua chiar dacă unele lipsesc
-  failed_packages=0
-  total_packages=${#BASE_PACKAGES[@]}
-  
+  # Initialize and update pacman keyring BEFORE installing packages
+  echo "Initializing pacman keyring..." >> /home/liveuser/Desktop/install.log
+  pacman-key --init &> /dev/null || echo "Warning: keyring init failed" >> /home/liveuser/Desktop/install.log
+  pacman-key --populate archlinux manjaro &> /dev/null || echo "Warning: keyring populate failed" >> /home/liveuser/Desktop/install.log
+  pacman -Sy --noconfirm archlinux-keyring 2>&1 >> /home/liveuser/Desktop/install.log || echo "Warning: failed to update keyring package" >> /home/liveuser/Desktop/install.log
+  # Refresh database to ensure package availability checks are accurate
+  pacman -Sy --noconfirm &> /dev/null || true
+
+  # Generate package availability report before installation
+  REPORT_PATH="/home/liveuser/Desktop/packages-report.txt"
+  : > "$REPORT_PATH"
   for package in "${BASE_PACKAGES[@]}"; do
-    if ! pacstrap /mnt "$package" 2>/dev/null; then
-      echo "Warning: Failed to install $package" >> /tmp/install.log
-      echo "FAILED: $package" >> /tmp/failed_packages.log
-      ((failed_packages++))
+    if pacman -Sp --noconfirm "$package" > /dev/null 2>&1; then
+      printf "%-28s %s\n" "$package" "OK" >> "$REPORT_PATH"
+    else
+      printf "%-28s %s\n" "$package" "NOT_OK" >> "$REPORT_PATH"
     fi
   done
-  
-  # Scrie statistici în log
-  echo "Installed: $((total_packages - failed_packages))/$total_packages packages" >> /tmp/install.log
-  
-  echo "21" | tr -d '\n' > /tmp/progress
+  update_progress "18"
 
-  # Generating fstab
-  if ! genfstab -U -p /mnt >> /mnt/etc/fstab; then
+  trap - ERR
+  failed_packages=0
+  total_packages=${#BASE_PACKAGES[@]}
+  installed_packages=0
+  
+  # Progress calculation: 18% to 70% for package installation (52% range for all packages)
+  for package in "${BASE_PACKAGES[@]}"; do
+    if ! pacstrap /mnt "$package" 2>/dev/null; then
+      echo "Warning: Failed to install $package" >> /home/liveuser/Desktop/install.log
+      echo "FAILED: $package" >> /tmp/failed_packages.log
+      ((failed_packages++))
+    else
+      ((installed_packages++))
+    fi
+    
+    # Update progress: 18% + (installed_packages / total_packages) * 52%
+    progress=$((18 + (installed_packages * 52 / total_packages)))
+    update_progress "$progress"
+  done
+  
+  trap 'error_exit "Unexpected error at line $LINENO"' ERR
+  
+  echo "Installed: $installed_packages/$total_packages packages" >> /home/liveuser/Desktop/install.log
+  
+  update_progress "70"
+
+  # Generating fstab (without deprecated -p) and logging stderr to desktop
+  if ! genfstab -U /mnt >> /mnt/etc/fstab 2>> /home/liveuser/Desktop/install.log; then
     error_exit "Failed to generate fstab"
   fi
-  echo "58" | tr -d '\n' > /tmp/progress
+  update_progress "72"
 
   # Pushing temporary Timezone to localtime file
   ln -sf /usr/share/zoneinfo/"$ZONE" /mnt/etc/localtime
-  echo "60" | tr -d '\n' > /tmp/progress
+  update_progress "74"
 
   # Enable or disable UTC time
   if $utc_enabled; then
@@ -216,7 +248,7 @@
     arch-chroot /mnt hwclock --systohc --localtime
   fi
   sed -i "s/#en_US.UTF-8/en_US.UTF-8/" /mnt/etc/locale.gen
-  echo "62" | tr -d '\n' > /tmp/progress
+  update_progress "76"
 
   # Passing custom locale to locale file
   if [ "$LOCALE" != "en_US.UTF-8" ]; then
@@ -225,7 +257,7 @@
 
   # making the language equal to the locale, and passing to locale.conf
   echo "LANG=$LOCALE" > /mnt/etc/locale.conf
-  echo "64" | tr -d '\n' > /tmp/progress
+  update_progress "78"
 
   # If there is a custom keymap, add it to the vconsole
   if [ "$KEYMAP" != "us" ]; then
@@ -237,21 +269,24 @@
 
   # Comitting the locale settings
   arch-chroot /mnt locale-gen &> /dev/null
-  echo "68" | tr -d '\n' > /tmp/progress
+  update_progress "80"
 
   # Setting the hostname
   echo "$HOST_NAME" > /mnt/etc/hostname
-  echo "70" | tr -d '\n' > /tmp/progress
+  update_progress "82"
 
   # Adding localhost to hosts file
   echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t$HOST_NAME.localdomain\t$HOST_NAME" >> /mnt/etc/hosts
-  echo "74" | tr -d '\n' > /tmp/progress
+  update_progress "84"
 
   # Partition layout work:
   if [ "$PARTITION_LAYOUT" != "Basic" ]; then
-    arch-chroot /mnt mkinitcpio -p linux &> /dev/null
+    arch-chroot /mnt mkinitcpio -p linux617 &> /dev/null
+    grep -q 'plymouth' /mnt/etc/mkinitcpio.conf || sed -i 's/^\(HOOKS=(\)/\1plymouth /' /mnt/etc/mkinitcpio.conf
+    arch-chroot /mnt mkinitcpio -P &> /dev/null
+
   fi
-  echo "78" | tr -d '\n' > /tmp/progress
+  update_progress "86"
 
   # Install GRUB for EFI or Legacy platform
   if $UEFI; then
@@ -263,18 +298,11 @@
       error_exit "Failed to install GRUB (Legacy mode)"
     fi
   fi
-  echo "81" | tr -d '\n' > /tmp/progress
-
-  # Add the grub theme to the configuration file
-  echo "GRUB_THEME=\"/usr/share/grub/themes/pearOS/theme.txt\"" >> /mnt/etc/default/grub
-  if ! arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg &> /dev/null; then
-    error_exit "Failed to generate GRUB configuration"
-  fi
-  echo "85" | tr -d '\n' > /tmp/progress
+  update_progress "88"
 
   # Change root password to "pear"
   arch-chroot /mnt chpasswd <<<"root:$root_passwd"
-  echo "87" | tr -d '\n' > /tmp/progress
+  update_progress "90"
 
   # Add post_install to autostart
   cp -r /usr/share/pearOS-installer/ /mnt/usr/share/
@@ -300,59 +328,72 @@
   arch-chroot /mnt useradd -m -g users -G wheel -s /bin/bash "default"
   arch-chroot /mnt chpasswd <<<"$USER_NAME:$user_passwd"
   arch-chroot /mnt usermod -aG wheel default
-  arch-chroot /mnt usermod -aG sudo default
+  # arch-chroot /mnt usermod -aG sudo default
   sed -i 's/# %wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/' /mnt/etc/sudoers
   echo "default ALL=(ALL) NOPASSWD:ALL" >> /mnt/etc/sudoers
-  echo "89" | tr -d '\n' > /tmp/progress
+  update_progress "92"
 
   # Adding pacman to conf and updating packages list
   cp /etc/pacman.conf /mnt/etc/pacman.conf
   arch-chroot /mnt pacman -Sy --quiet --noconfirm 2>/dev/null || true
-  echo "90" | tr -d '\n' > /tmp/progress
-
-  # Installing yay helper
-  arch-chroot /mnt bash -c "cd /tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm" 2>/dev/null || echo "Warning: Failed to install yay" >> /tmp/install.log
-
-  # Installing plymouth
-  arch-chroot /mnt yay -S plymouth --noconfirm 2>/dev/null || echo "Warning: Failed to install plymouth" >> /tmp/install.log
+  update_progress "93"
 
   # Setting pearOS plymouth theme
-  plymouth-set-default-theme -R pear-plymouth 2>/dev/null || echo "Warning: Failed to set plymouth theme" >> /tmp/install.log
+  arch-chroot /mnt plymouth-set-default-theme -R pear-plymouth 2>/dev/null || echo "Warning: Failed to set plymouth theme" >> /home/liveuser/Desktop/install.log
 
   # Enable Network Manager, vbox additions and SDDM services
   arch-chroot /mnt systemctl enable NetworkManager.service &> /dev/null
   arch-chroot /mnt systemctl enable sddm.service &> /dev/null
-  arch-chroot /mnt systemctl enable vboxservice.service &>/dev/null
-  echo "92" | tr -d '\n' > /tmp/progress
+  update_progress "94"
 
   # Enabling auto-login for 'default' user :
   echo "[Autologin]" > /mnt/etc/sddm.conf
   echo "User=default" >> /mnt/etc/sddm.conf
   echo "Session=plasma.desktop" >> /mnt/etc/sddm.conf
-  echo "94" | tr -d '\n' > /tmp/progress
+  update_progress "95"
 
   # Enable bluetooth addons if needed
   if $bluetooth_enabled; then
     arch-chroot /mnt systemctl enable bluetooth.service &> /dev/null
-    echo "95" | tr -d '\n' > /tmp/progress
   fi
 
   # Fix extras files permissions (fixes the theme-switcher bug
   chmod -R 0777 /mnt/usr/share/extras
-  echo "95" | tr -d '\n' > /tmp/progress
+  update_progress "96"
+
+  # Install pearOS boot chime
+  arch-chroot /mnt git clone https://github.com/Pear-Project/pearos-boot-sound.git 2>/dev/null || true
+  if [ -d /mnt/pearos-boot-sound ]; then
+    arch-chroot /mnt chmod +x pearos-boot-sound/install.sh
+    arch-chroot /mnt ./pearos-boot-sound/install.sh 2>/dev/null || echo "Warning: Failed to install boot chime" >> /home/liveuser/Desktop/install.log
+  fi
+  update_progress "97"
 
   # Check if the user installs pearOS in a VM, if yes, which, then enabled corresponding services
   if [ "$hypervisor" != "none" ]; then
     if [ "$hypervisor" = "oracle" ]; then
       arch-chroot /mnt systemctl enable vboxservice.service &> /dev/null
-      echo "98" | tr -d '\n' > /tmp/progress
+      update_progress "98"
     elif [ "$hypervisor" = "vmware" ]; then
       arch-chroot /mnt systemctl enable vmtoolsd.service &> /dev/null
       arch-chroot /mnt systemctl enable vmware-vmblock-fuse.service &> /dev/null
-      echo "98" | tr -d '\n' > /tmp/progress
+      update_progress "98"
     fi
+  else
+    update_progress "98"
   fi
-  echo "98" | tr -d '\n' > /tmp/progress
+
+    # Add the grub theme to the configuration file
+  echo "GRUB_THEME=\"/usr/share/grub/themes/pearOS/theme.txt\"" >> /mnt/etc/default/grub
+  sudo sed -i 's|^GRUB_CMDLINE_LINUX=.*|GRUB_CMDLINE_LINUX="quiet splash loglevel=3"|' /mnt/etc/default/grub
+
+  if ! arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg &> /dev/null; then
+    error_exit "Failed to generate GRUB configuration"
+  fi
+
+  update_progress "99"
+  rm -rf /mnt/usr/share/applications/assistant.desktop /mnt/usr/share/applications/qdbusviewer.desktop /mnt/usr/share/applications/linguist.desktop /mnt/usr/share/applications/designer.desktop /mnt/usr/share/applications/linguist.desktop /mnt/usr/share/applications/lstopo.desktop /mnt/usr/share/applications/linguist.desktop /mnt/usr/share/applications/kvantummanager.desktop /mnt/usr/share/applications/org.kde.drkonqi.coredump.gui.desktop /mnt/usr/share/applications/electron38.desktop /mnt/usr/share/applications/org.kde.plasma.emojier.desktop /mnt/usr/share/applications/kde_wacom_tabletfinder.desktop
+  arch-chroot /mnt pacman -R --noconfirm plasma-welcome
 
   # Sends the install finished messages to the frontend
   if [ -f /tmp/failed_packages.log ]; then
